name: sample_gru_avg  # any name or null
module: gru # tra_lstm2 # 'LSTM' # 'TRA_LSTM' # 'GeneralRNN' # patch_tst # lgbm , gru_dsize
submodels: [best , swalast , swabest]

labels: 
  - std_lag1_10 # rtn_lag1_10 # std_lag1_10
input.type: data

input.data.types: day # 'day+30m' , 30m , day
input.data.prenorm:
  day: {'divlast' : True  , 'histnorm' : True}

input.hidden.types:
  - gru_day.0.best
  - gru_day.0.swabest

beg_date:   20170103 # 20220613 # 20170103
end_date:   99991231
interval:   120
window:    2400