# For predictions
# prediction name
#   name: module_name
#   submodel: submodel_type , best , swalast , swabest
#   num: num , a valid number or all
prediction: 
  gru_day_V0:
    name: gru_day
    submodel: swalast
    num: 0

  gruRTN_day_V0:
    name: gruRTN_day
    submodel: swalast
    num: 0

  gru_day_V1:
    name: gru_avg
    submodel: swalast
    num: all

# For hidden extraction : 
# hidden name
#   name: module_name
#   submodels: submodel_types , best , swalast , swabest
#   nums: a list of valid numbers or NULL (all)
hidden_extraction:
  gru_day_V0: 
    name: gru_day
    submodels: [best]
    nums: NULL

# db mapping models , type: db | factor | pred
# prediction name
#   src: db_src          .db_src or factor or pred
#   key: db_key          .if db_src is db, db_key is the key of the db, otherwise it is the name of the factor or pred
#   col: column_name     .use feature to load the data
db_mapping: 
  scores_v0:
    src: sellside
    key: dongfang.scores_v0
    col: avg

  master_combined:
    src: sellside
    key: huatai.master_combined
    col: master_combined