# Genetic Programming parameters
# most frequently  changing variables
gp_fac_list: [cp, turn, vol, amt, op, hp, lp, vp, bp, ep, ocfp, dp, adv20, adv60]       # gp intial factor list, in lower case
gp_raw_list: [CP, TURN, VOL, AMT, OP, HP, LP, VP, BP, EP, OCFP, DP, ADV20, ADV60 , RTN] # gp intial raw data list, in upper case
slice_date : # 修改数据切片区间,前两个为样本内的起止点,后两个为样本外的起止点均需要是交易日
  - '2010-01-04'
  - '2021-12-31'
  - '2022-01-04'
  - '2099-12-31'
fitness_wgt: 
  rankic_in_res:  1.
  rankir_in_res:  1.
  rankic_out_res: 0.
  rankir_out_res: 0.
  rankic_in_raw:  0.
  rankir_in_raw:  0.
  rankic_out_raw: 0.
  rankir_out_raw: 0.

show_progress:    False   # if show some text
pop_num:          300     # [parameter] population number , recommended to be 3000
hof_num:          50      # [parameter] halloffame number , recommended to be 500
elite_num:        10      # [parameter] elite number (max) , recommended to be 100

n_iter :          2       # [outer loop] loop number
n_gen:            3       # [inner loop] generation number
max_depth:        5       # [inner loop] max tree depth of gp
select_offspring: nsga2   # [inner loop] can be 'best' , '2Tour' , 'Tour' , 'nsga2'
surv_rate:        0.6     # [inner loop] use survive rate in best selection
cxpb:             0.35    # [inner loop] crossover probability
mutpb:            0.25    # [inner loop] mutation probability
ir_floor:         3.0     # [outer loop] rankir threshold , recommended to be 3.0
ir_floor_decay:   1.0     # [outer loop] rankir threshold decay factor for iterations , recommended to be 1.0
corr_cap:         0.6     # [outer loop] cap of correlation with existing factors , recommended to be 0.6

labels_neut_type: all     # [outer loop] what factors to neutralize labels: 'svd' , 'all' , recommended to be 'all'
svd_mat_method:   coef_ts # [outer loop] what matrix to svd in trying to lower the dimensions of factors to neutralize labels: 'total' , 'coef_ts'
svd_top_ratio:    0.75    # [outer loop] svd factor: least explanatory ratio
svd_top_n:        1       # [outer loop] svd factor: least factors
factor_neut_type: 0       # [outer loop] how to neutralize factor values when i_iter > 0; 0: no neutral , 1: one-time neutral giving insample beta, 2: neutral every day

test_params:
  gp_fac_list: [cp, turn]
  gp_raw_list: [CP, TURN]
  slice_date : 
    - '2022-01-04'
    - '2022-12-30'
    - '2023-01-04'
    - '2023-12-29'
  show_progress: True 
  pop_num: 2
  hof_num: 1
  n_gen: 2 
  n_iter: 2 
  max_depth: 2 
  ir_floor: 1.
  corr_cap: 0.7 
  ir_floor_decay: 0.9 
  neut_method: 0