max_epoch:  200
batch_size: 10000
skip_horizon:  20 # must be larger than span of labels 
fitting_step:  5
callbacks:
  - StatusDisplay
  # - BatchDisplay
  - BasicTestResult
  - DetailedAlphaAnalysis
  - EarlyStoppage
  - EarlyExitRetrain
  - NanLossRetrain
  - ValidationConverge
  # - TrainConverge
  # - FitConverge
  # - CallbackTimer
  # - CudaEmptyCache

dataloader.sample_method:   sequential # total_shuffle , sequential , both_shuffle , train_shuffle
dataloader.shuffle_option:  epoch # static , init , epoch
dataloader.train_ratio:     0.8

trainer.transfer:  false
trainer.optimizer: {'name' : 'Adam' , 'param' : {} ,}  # 'ADAM' , 'SGD' , 'SAM' , 'FSAM' , 'GAM' , 'ASAM' , 'GSAM'
trainer.scheduler: {'name' : 'cycle' , 'param' : {'base_lr': 1.0e-7 , 'step_size_up': 4} ,}  #{'name' : 'SGD' , 'param' : {} ,}
trainer.learn_rate: {'base' : 0.005 , 'transfer_multiplier' : {'encoder' : 0.1 , 'decoder' : 1.0, }}
trainer.gradient.clip_value: 10.0

# loss params , should be a dict, 
# keys (e.g. 'ccc', 'hidden_corr', 'hidden_corr_deprecated') and loss_kwargs (e.g. {'lamb' :  0.001 ,}) 
# the first key is the primary one to be used for multilosses
criterion.loss: 
  ccc: {}  
  # mse: {}
  # pearson: {}
  hidden_corr:  {'lamb' :  0. ,}
  hidden_corr_deprecated:  {'lamb' :  0.001 ,}

# score params , should be a dict, can be one of mse, pearson, ccc, spearman
# it is used for validation set calculation and early stopping
# only one score criterion is allowed
criterion.score:     
  spearman: {which_output: [0] , which_label: [0]}
  # mse, pearson, ccc, spearman

criterion.weight:
  fit:    'equal' # 'top'
  test:   'equal' # 'top'

# multilosses params , should be a dict, 
# keys (e.g. 'hybrid', 'dwa', 'ruw', 'ewa', 'gls', 'rws') and multilosses_kwargs (e.g. {'phi' : null , 'tau' : 2}) 
# only one multilosses criterion is allowed
criterion.multilosses:
  name: hybrid # ewa, hybrid, dwa, ruw, gls, rws
  params:  
    hybrid: {'phi' : null , 'tau' : 2}
    dwa: {'tau' : 2}
    ruw: {'phi' : null}
    ewa: {}
    gls: {}
    rws: {}