console:
  class: logging.StreamHandler
  formatter: levelcolor
  formatter_class: _LevelColorFormatter
  level: DEBUG
  param: {}
datefmt: '%y-%m-%d %H:%M:%S'
file:
  class: logging.handlers.TimedRotatingFileHandler
  formatter: level
  formatter_class: _LevelFormatter
  level: DEBUG
  param:
    backupCount: 5
    encoding: utf-8
    filename: project_log.log
    when: D
formatters:
  color:
    fmt: '%(log_color)s%(asctime)s|LEVEL:%(levelname)-9s|%(reset_log_color)s: %(message_log_color)s%(message)s'
    log_colors:
      DEBUG: bold,white,bg_light_black
      INFO: bold,white,bg_green
      WARNING: bold,black,bg_yellow
      ERROR: bold,white,bg_red
      CRITICAL: bold,white,bg_purple
    secondary_log_colors:
      message:
        DEBUG: bold,light_black
        INFO: bold,green
        ERROR: bold,red
        WARNING: bold,yellow
        CRITICAL: bold,white,bg_purple
      reset:
        DEBUG: reset
        INFO: reset
        WARNING: reset
        ERROR: reset
        CRITICAL: reset
  level:
    fmt: '%(asctime)s|LEVEL:%(levelname)-9s|: %(message)s'
    # level_fmts:
    #  DEBUG: '%(message)s'
    #  INFO: '%(message)s'
  levelcolor:
    fmt: '%(log_color)s%(asctime)s|LEVEL:%(levelname)-9s|%(reset_log_color)s: %(message_log_color)s%(message)s'
    #level_fmts:
    #  DEBUG: '%(message_log_color)s%(message)s'
    #  INFO: '%(message_log_color)s%(message)s'
    log_colors:
      DEBUG: bold,white,bg_light_black
      INFO: bold,white,bg_green
      WARNING: bold,black,bg_yellow
      ERROR: bold,white,bg_red
      CRITICAL: bold,white,bg_purple
    secondary_log_colors:
      message:
        DEBUG: bold,light_black
        INFO: bold,green
        ERROR: bold,red
        WARNING: bold,yellow
        CRITICAL: bold,white,bg_purple
      reset:
        DEBUG: reset
        INFO: reset
        WARNING: reset
        ERROR: reset
        CRITICAL: reset
  standard:
    fmt: '%(asctime)s|LEVEL:%(levelname)-9s|: %(message)s'
handlers:
- console
- file
level: DEBUG
name: default_log
