# For predictions
# prediction name
#   name: module_name
#   submodel: submodel_type , best , swalast , swabest
#   num: num , a valid number or all
prediction: 
  gru_day_V0:
    name: gru@gru_day
    submodel: swalast
    num: 0

  gruRTN_day_V0:
    name: gru@gruRTN_day
    submodel: swalast
    num: 0

  gru_day_V1:
    name: gru@gru_avg
    submodel: swalast
    num: all

# For hidden extraction : 
# hidden name
#   name: module_name
#   submodels: submodel_types , best , swalast , swabest
#   nums: a list of valid numbers or NULL (all)
hidden_extraction:
  gru_day_V0: 
    name: gru@gru_day
    submodels: [best]
    nums: NULL